[package]
name = "vsbm"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "28.0.0"
anyhow = "1.0.101"
pollster = "0.4.0"
winit = "0.30.12"
bytemuck = "1.25.0"
clap = { version = "4.5.58", features = ["derive"] }
env_logger = "0.11.9"
log = "0.4.29"